services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vanilla-web-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d vanilla-web-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: ./web
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/vanilla-web-db
    volumes:
      - ./web:/app
      - ./tools:/app/tools
    depends_on:
      - db

volumes:
  db_data: